"""zeroos config — Manage agent configuration."""

import json
import os
from datetime import datetime, timezone

import click
import yaml

ZEROOS_DIR = os.path.expanduser("~/.zeroos")
CONFIG_PATH = os.path.join(ZEROOS_DIR, "config.yaml")
STATE_DIR = os.path.join(ZEROOS_DIR, "state")

VALID_PRESETS = ["conservative", "balanced", "degen", "funding"]
PRESET_MAX_POSITIONS = {"conservative": 2, "balanced": 3, "degen": 6, "funding": 4}

PAPER_MIN_HOURS = 24
PAPER_MIN_TRADES = 50


def _load_config() -> dict:
    if not os.path.exists(CONFIG_PATH):
        click.echo("  ✗ Not initialized. Run `zeroos init` first.")
        raise SystemExit(1)
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def _save_config(cfg: dict):
    with open(CONFIG_PATH, "w") as f:
        f.write("# ZERO OS Agent Configuration\n")
        f.write("# Generated by: zeroos init\n")
        f.write("# Docs: https://docs.getzero.dev/config\n\n")
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
    os.chmod(CONFIG_PATH, 0o600)


def _check_paper_eligibility() -> tuple[bool, str]:
    """Check if the paper period minimum is met (24h or 50 trades)."""
    trades_path = os.path.join(STATE_DIR, "trades.json")
    heartbeat_path = os.path.join(STATE_DIR, "heartbeat.json")

    trade_count = 0
    if os.path.exists(trades_path):
        try:
            with open(trades_path) as f:
                trades = json.load(f)
            if isinstance(trades, list):
                trade_count = len(trades)
        except (json.JSONDecodeError, OSError):
            pass

    if trade_count >= PAPER_MIN_TRADES:
        return True, f"{trade_count} paper trades completed"

    hours_elapsed = 0
    if os.path.exists(heartbeat_path):
        try:
            with open(heartbeat_path) as f:
                hb = json.load(f)
            started = datetime.fromisoformat(hb.get("started_at", ""))
            hours_elapsed = (datetime.now(timezone.utc) - started).total_seconds() / 3600
        except Exception:
            pass

    if hours_elapsed >= PAPER_MIN_HOURS:
        return True, f"{hours_elapsed:.1f}h of paper trading"

    return False, f"Need {PAPER_MIN_HOURS}h or {PAPER_MIN_TRADES} trades (have {hours_elapsed:.1f}h, {trade_count} trades)"


@click.command()
@click.option("--live", "go_live", is_flag=True, help="Switch to live trading mode.")
@click.option("--paper", "go_paper", is_flag=True, help="Switch to paper trading mode.")
@click.option("--preset", "preset_name", type=click.Choice(VALID_PRESETS), help="Change agent preset.")
@click.option("--x402", "x402_wallet", type=str, help="Set x402 payment wallet address.")
def config(go_live, go_paper, preset_name, x402_wallet):
    """Manage ZERO OS agent configuration."""
    if not any([go_live, go_paper, preset_name, x402_wallet]):
        cfg = _load_config()
        click.echo()
        click.echo("  Current configuration:")
        click.echo(f"  Mode:     {cfg.get('agent', {}).get('mode', '?')}")
        click.echo(f"  Preset:   {cfg.get('agent', {}).get('preset', '?')}")
        click.echo(f"  x402:     {cfg.get('signals', {}).get('x402_wallet') or 'not set'}")
        click.echo(f"  Network:  {cfg.get('hyperliquid', {}).get('network', '?')}")
        click.echo()
        return

    cfg = _load_config()

    if go_live:
        if cfg.get("agent", {}).get("mode") == "live":
            click.echo("  Already in live mode.")
            return
        eligible, reason = _check_paper_eligibility()
        if not eligible:
            click.echo(f"  ✗ Cannot switch to live yet. {reason}")
            raise SystemExit(1)
        cfg["agent"]["mode"] = "live"
        _save_config(cfg)
        click.echo(f"  ✓ Switched to LIVE mode. ({reason})")
        click.echo("  ⚠ Real money will be used on next start. Be careful.")

    if go_paper:
        cfg["agent"]["mode"] = "paper"
        _save_config(cfg)
        click.echo("  ✓ Switched to PAPER mode.")

    if preset_name:
        cfg["agent"]["preset"] = preset_name
        cfg["agent"]["name"] = preset_name
        cfg["execution"]["max_positions"] = PRESET_MAX_POSITIONS.get(preset_name, 3)
        _save_config(cfg)
        click.echo(f"  ✓ Preset changed to: {preset_name}")

    if x402_wallet:
        cfg["signals"]["x402_wallet"] = x402_wallet
        _save_config(cfg)
        click.echo(f"  ✓ x402 wallet set: {x402_wallet}")
