"""zeroos config — manage agent configuration."""

import json
import os
from datetime import datetime, timezone

import click
import yaml

from scanner.zeroos_cli.style import Z

ZEROOS_DIR = os.path.expanduser("~/.zeroos")
CONFIG_PATH = os.path.join(ZEROOS_DIR, "config.yaml")
STATE_DIR = os.path.join(ZEROOS_DIR, "state")

VALID_PRESETS = ["conservative", "balanced", "degen", "funding"]
PRESET_MAX_POSITIONS = {"conservative": 2, "balanced": 3, "degen": 6, "funding": 4}

PAPER_MIN_HOURS = 24
PAPER_MIN_TRADES = 50


def _load_config() -> dict:
    if not os.path.exists(CONFIG_PATH):
        print(f'  {Z.fail("not initialized. run:")} {Z.lime("$ zeroos init")}')
        raise SystemExit(1)
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def _save_config(cfg: dict):
    with open(CONFIG_PATH, "w") as f:
        f.write("# zero os agent configuration\n")
        f.write("# generated by: zeroos init\n")
        f.write("# docs: https://getzero.dev/docs\n\n")
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
    os.chmod(CONFIG_PATH, 0o600)


def _check_paper_eligibility() -> tuple[bool, str]:
    trades_path = os.path.join(STATE_DIR, "trades.json")
    heartbeat_path = os.path.join(STATE_DIR, "heartbeat.json")

    trade_count = 0
    if os.path.exists(trades_path):
        try:
            with open(trades_path) as f:
                trades = json.load(f)
            if isinstance(trades, list):
                trade_count = len(trades)
        except (json.JSONDecodeError, OSError):
            pass

    if trade_count >= PAPER_MIN_TRADES:
        return True, f"{trade_count} paper trades completed"

    hours_elapsed = 0
    if os.path.exists(heartbeat_path):
        try:
            with open(heartbeat_path) as f:
                hb = json.load(f)
            started = datetime.fromisoformat(hb.get("started_at", ""))
            hours_elapsed = (datetime.now(timezone.utc) - started).total_seconds() / 3600
        except Exception:
            pass

    if hours_elapsed >= PAPER_MIN_HOURS:
        return True, f"{hours_elapsed:.1f}h of paper trading"

    return False, f"need {PAPER_MIN_HOURS}h or {PAPER_MIN_TRADES} trades (have {hours_elapsed:.1f}h, {trade_count} trades)"


@click.command()
@click.option("--live", "go_live", is_flag=True, help="Switch to live trading mode.")
@click.option("--paper", "go_paper", is_flag=True, help="Switch to paper trading mode.")
@click.option("--preset", "preset_name", type=click.Choice(VALID_PRESETS), help="Change agent preset.")
def config(go_live, go_paper, preset_name):
    """Manage ZERO OS agent configuration."""
    if not any([go_live, go_paper, preset_name]):
        cfg = _load_config()
        print()
        print(f'  {Z.logo()}')
        print()
        print(f'  {Z.rule()}')
        print()
        print(f'  {Z.header("CONFIGURATION")}')
        print(f'  {Z.dots("mode", cfg.get("agent", {}).get("mode", "?"))}')
        print(f'  {Z.dots("preset", cfg.get("agent", {}).get("preset", "?"))}')
        print(f'  {Z.dots("signals", "subscription (via zero os)")}')
        print(f'  {Z.dots("network", cfg.get("hyperliquid", {}).get("network", "?"))}')
        print()
        return

    cfg = _load_config()

    if go_live:
        if cfg.get("agent", {}).get("mode") == "live":
            print(f'  {Z.dim("already in live mode.")}')
            return
        eligible, reason = _check_paper_eligibility()
        if not eligible:
            print(f'  {Z.fail(f"cannot switch to live yet. {reason}")}')
            raise SystemExit(1)

        print()
        print(f'  {Z.logo()}')
        print()
        print(f'  {Z.rule()}')
        print()
        print(f'  {Z.warn("live mode trades with real money.")}')
        print()
        print(f'  {Z.dim("live mode includes pro features:")}')
        print(f'  {Z.dim("▸ full reasoning engine (11 indicators, regime detection)")}')
        print(f'  {Z.dim("▸ collective intelligence (learned from the network)")}')
        print(f'  {Z.dim("▸ arena + zero score")}')
        print(f'  {Z.dim("▸ up to 3 agents")}')
        print()
        print(f'  {Z.dim("performance fee: 10% of net profit per trade.")}')
        print(f'  {Z.dim("▸ on losses: zero receives nothing")}')
        print(f'  {Z.dim("▸ high-water mark: you only pay on new highs")}')
        print(f'  {Z.dim("▸ every fee is on-chain and verifiable")}')
        print()

        confirm = click.prompt(f'  {Z.dim("type CONFIRM to go live")}', type=str)
        if confirm != "CONFIRM":
            print(f'  {Z.dim("cancelled.")}')
            return

        cfg["agent"]["mode"] = "live"
        cfg.setdefault("subscription", {})["plan"] = "pro"
        cfg["subscription"]["status"] = "active"
        cfg["subscription"]["fee_consent"] = datetime.now(timezone.utc).isoformat()
        _save_config(cfg)
        print()
        print(f'  {Z.success(f"switched to live mode. ({reason})")}')
        print(f'  {Z.dim("performance fee active. zero earns nothing on losses.")}')

    if go_paper:
        cfg["agent"]["mode"] = "paper"
        _save_config(cfg)
        print(f'  {Z.success("switched to paper mode.")}')

    if preset_name:
        cfg["agent"]["preset"] = preset_name
        cfg["agent"]["name"] = preset_name
        cfg["execution"]["max_positions"] = PRESET_MAX_POSITIONS.get(preset_name, 3)
        _save_config(cfg)
        print(f'  {Z.success(f"preset changed to: {preset_name}")}')
