"""zeroos dashboard — manage dashboard connection."""

import os
import secrets

import click
import yaml

from scanner.zeroos_cli.style import Z

ZEROOS_DIR = os.path.expanduser("~/.zeroos")
CONFIG_PATH = os.path.join(ZEROOS_DIR, "config.yaml")


def _load_config() -> dict:
    if not os.path.exists(CONFIG_PATH):
        print(f'  {Z.fail("not initialized. run:")} {Z.lime("$ zeroos init")}')
        raise SystemExit(1)
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def _save_config(cfg: dict):
    with open(CONFIG_PATH, "w") as f:
        f.write("# zero os agent configuration\n")
        f.write("# generated by: zeroos init\n")
        f.write("# docs: https://getzero.dev/docs\n\n")
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
    os.chmod(CONFIG_PATH, 0o600)


@click.command()
@click.option("--connect", is_flag=True, help="Generate token and connect to dashboard.")
@click.option("--disconnect", is_flag=True, help="Disconnect from dashboard.")
@click.option("--status", "show_status", is_flag=True, help="Show dashboard connection status.")
def dashboard(connect, disconnect, show_status):
    """Manage dashboard connection."""
    cfg = _load_config()

    print()
    print(f'  {Z.logo()}')
    print()

    if connect:
        token = secrets.token_urlsafe(32)
        if "telemetry" not in cfg:
            cfg["telemetry"] = {}
        cfg["telemetry"]["token"] = token
        cfg["telemetry"]["enabled"] = True
        _save_config(cfg)

        dashboard_url = cfg.get("telemetry", {}).get("dashboard_url", "https://getzero.dev")

        print(f'  {Z.success("dashboard connected.")}')
        print()
        print(f'  {Z.dots("url", f"{dashboard_url}/app?token={token}")}')
        print(f'  {Z.dots("token", token)}')
        print()
        print(f'  {Z.dim("open the url above to view your agent in real time.")}')
        print(f'  {Z.lime("$ zeroos dashboard --disconnect")}  {Z.dim("to stop sharing")}')

    elif disconnect:
        if "telemetry" in cfg:
            cfg["telemetry"]["token"] = None
            cfg["telemetry"]["enabled"] = False
        _save_config(cfg)
        print(f'  {Z.success("dashboard disconnected. telemetry stopped.")}')

    elif show_status:
        print(f'  {Z.rule()}')
        print()
        token = cfg.get("telemetry", {}).get("token")
        enabled = cfg.get("telemetry", {}).get("enabled", False)
        if token and enabled:
            dashboard_url = cfg.get("telemetry", {}).get("dashboard_url", "https://getzero.dev")
            print(f'  {Z.dots("dashboard", f"{Z.GREEN}● connected{Z.RESET}")}')
            print(f'  {Z.dots("url", f"{dashboard_url}/app?token={token}")}')
            print(f'  {Z.dots("token", f"{token[:8]}...{token[-4:]}")}')
        else:
            print(f'  {Z.dots("dashboard", "not connected")}')
            print(f'  {Z.lime("$ zeroos dashboard --connect")}  {Z.dim("to generate a token")}')

    else:
        print(f'  {Z.dim("specify --connect, --disconnect, or --status.")}')

    print()
