"""zeroos dashboard — Manage dashboard connection."""

import os
import secrets

import click
import yaml

ZEROOS_DIR = os.path.expanduser("~/.zeroos")
CONFIG_PATH = os.path.join(ZEROOS_DIR, "config.yaml")


def _load_config() -> dict:
    if not os.path.exists(CONFIG_PATH):
        click.echo("  ✗ Not initialized. Run `zeroos init` first.")
        raise SystemExit(1)
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def _save_config(cfg: dict):
    with open(CONFIG_PATH, "w") as f:
        f.write("# ZERO OS Agent Configuration\n")
        f.write("# Generated by: zeroos init\n")
        f.write("# Docs: https://docs.getzero.dev/config\n\n")
        yaml.dump(cfg, f, default_flow_style=False, sort_keys=False)
    os.chmod(CONFIG_PATH, 0o600)


@click.command()
@click.option("--connect", is_flag=True, help="Generate token and connect to dashboard.")
@click.option("--disconnect", is_flag=True, help="Disconnect from dashboard.")
@click.option("--status", "show_status", is_flag=True, help="Show dashboard connection status.")
def dashboard(connect, disconnect, show_status):
    """Manage dashboard connection."""
    cfg = _load_config()

    if connect:
        token = secrets.token_urlsafe(32)
        if "telemetry" not in cfg:
            cfg["telemetry"] = {}
        cfg["telemetry"]["token"] = token
        cfg["telemetry"]["enabled"] = True
        _save_config(cfg)

        dashboard_url = cfg.get("telemetry", {}).get("dashboard_url", "https://getzero.dev")

        click.echo()
        click.echo("  ✓ Dashboard connected.")
        click.echo()
        click.echo(f"  URL:   {dashboard_url}/app?token={token}")
        click.echo(f"  Token: {token}")
        click.echo()
        click.echo("  Open the URL above to view your agent in real time.")
        click.echo("  Run `zeroos dashboard --disconnect` to stop sharing.")
        click.echo()

    elif disconnect:
        if "telemetry" in cfg:
            cfg["telemetry"]["token"] = None
            cfg["telemetry"]["enabled"] = False
        _save_config(cfg)
        click.echo("  ✓ Dashboard disconnected. Telemetry stopped.")

    elif show_status:
        token = cfg.get("telemetry", {}).get("token")
        enabled = cfg.get("telemetry", {}).get("enabled", False)
        click.echo()
        if token and enabled:
            dashboard_url = cfg.get("telemetry", {}).get("dashboard_url", "https://getzero.dev")
            click.echo("  DASHBOARD: connected")
            click.echo(f"  URL:       {dashboard_url}/app?token={token}")
            click.echo(f"  Token:     {token[:8]}...{token[-4:]}")
        else:
            click.echo("  DASHBOARD: not connected")
            click.echo("  Run `zeroos dashboard --connect` to generate a token.")
        click.echo()

    else:
        click.echo("  Specify --connect, --disconnect, or --status.")
